# This workflow is triggered when a new tag is created in the repository
name: Build and push Docker image

on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository code
        uses: actions/checkout@v2
      
      # Build and tag the Docker image with the latest tag
      - name: Build Docker image and tag
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myapp:${{  github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          labels: ${{ steps.meta.outputs.labels }}
      
      # Login to Docker Hub using user and password secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Push the Docker image to Docker Hub with the latest tag and the tag that triggered the workflow
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myapp:${{  github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          labels: ${{ steps.meta.outputs.labels }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
