# This workflow is triggered whenever a new tag is created in the repository
name: Build and push Docker image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      # Checkout the code from the repository
      - name: Checkout repository code
        uses: actions/checkout@v2
      
      # Build and tag the Docker image with the latest tag and the 'latest' tag
      - name: Build Docker image and tag with latest
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            yourdockerhubusername/yourimagename:${{ github.ref }}
            yourdockerhubusername/yourimagename:latest
      
      # Login to Docker Hub using the provided username and password secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      # Push the Docker image to Docker Hub with the latest tag and the tag that triggered the workflow
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
